### ISSUE TITLE
Doesn't work with out-of-the-box docker Ignite image

### ISSUE THREAD

**Issue by sturfee-petrl** [amsokol/ignite-go-client#27]
I am trying to get started with ignite. 

From these [docs](https://apacheignite.readme.io/docs/docker-deployment)
> sudo docker run -it --net=host -e "CONFIG_URI=https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-cache.xml" apacheignite/ignite

Ignite works fine. I tested it with python script
```python
from pyignite import Client

client = Client()
client.connect('127.0.0.1', 10800)

#Create cache
my_cache = client.create_cache('my cache')

#Put value in cache
my_cache.put('my key', 42)
```

But if I try to access it with the go library. Then I have following errors. I used any your example
#### go
> failed connect to server: failed to open connection: EOF
#### java from ignite logs
```
[22:24:37,694][SEVERE][grid-nio-worker-client-listener-2-#31][ClientListenerProcessor] Closing NIO session because of unhandled exception.
class org.apache.ignite.IgniteCheckedException: Invalid handshake message
	at org.apache.ignite.internal.processors.odbc.ClientListenerNioServerBuffer.read(ClientListenerNioServerBuffer.java:115)
	at org.apache.ignite.internal.processors.odbc.ClientListenerBufferedParser.decode(ClientListenerBufferedParser.java:60)
	at org.apache.ignite.internal.processors.odbc.ClientListenerBufferedParser.decode(ClientListenerBufferedParser.java:40)
	at org.apache.ignite.internal.util.nio.GridNioCodecFilter.onMessageReceived(GridNioCodecFilter.java:114)
	at org.apache.ignite.internal.util.nio.GridNioFilterAdapter.proceedMessageReceived(GridNioFilterAdapter.java:109)
	at org.apache.ignite.internal.util.nio.GridNioServer$HeadFilter.onMessageReceived(GridNioServer.java:3553)
	at org.apache.ignite.internal.util.nio.GridNioFilterChain.onMessageReceived(GridNioFilterChain.java:175)
	at org.apache.ignite.internal.util.nio.GridNioServer$ByteBufferNioClientWorker.processRead(GridNioServer.java:1132)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.processSelectedKeysOptimized(GridNioServer.java:2389)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.bodyInternal(GridNioServer.java:2156)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.body(GridNioServer.java:1797)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:748)
```

I saw [instructions about ignite installation](https://github.com/amsokol/ignite-go-client#how-to-run-tests). And here I found **[setup from docker container](https://hub.docker.com/r/apacheignite/ignite/dockerfile)**. Container call `CMD ./run.sh`. And these sources I found [here](https://github.com/apache/ignite/tree/master/docker/apache-ignite). 

As I think only difference what I see is that `run.sh` doesn't do step **6** `/bin/control.bat --activate `. 

I need to migrate Ignite cluster under kubernetes and there we will use only docker containers. And actually it's much easier to use docker.

Thank you!

**Comment by amsokol** [comment]
Hi,

All my examples assume Ignite is configured with TLS and login/password.
If you want connect to vanilla Docker Ignite (not recommended for production) please try to comment TLS and credentials code for connect:
```go
import (
    "github.com/amsokol/ignite-go-client/binary/v1"
)

ctx := context.Background()

// connect
c, err := ignite.Connect(ctx, ignite.ConnInfo{
    Network: "tcp",
    Host:    "localhost",
    Port:    10800,
    Major:   1,
    Minor:   1,
    Patch:   0,
    // Credentials are only needed if they're configured in your Ignite server.
    /*
    Username: "ignite",
    Password: "ignite",
    */
    Dialer: net.Dialer{
        Timeout: 10 * time.Second,
    },
    // Don't set the TLSConfig if your Ignite server
    // isn't configured with any TLS certificates.
    /*
    TLSConfig: &tls.Config{
        // You should only set this to true for testing purposes.
        InsecureSkipVerify: true,
    },
    */
})
if err != nil {
    t.Fatalf("failed connect to server: %v", err)
}
defer c.Close()
```
and let me know result plz.

**Comment by sturfee-petrl** [comment]
Yeah! It works!

**Comment by sturfee-petrl** [comment]
@amsokol Today I started to work with Ignite again and I again hit the same error and I again spent half of day. This time I could figured out it myself. **I wanted to open an issue when I found this one ... what interesting which was written by me a half year back.** 

```
	if ci.TLSConfig != nil {
		conn, err = tls.DialWithDialer(&ci.Dialer, ci.Network, address, ci.TLSConfig)
	} else {
		conn, err = ci.Dialer.Dial(ci.Network, address)
	}
```
Is it not implicit construction? 
It's definitely confuse people as it's used as a boolean flag. 
No many people actually need some special settings in TLSConfig. As you mentioned from my experience I used it only for debug.
